import discord
from discord.ext import commands
import asyncio

class lyriccommands:
    """lyriccommands"""

    def __init__(self, bot):
        self.bot = bot
        sleep = asyncio.sleep
        sing = self.bot.say
        
    @commands.command()
    async def fuckthisshit(self):
        """Fuck this shit I'm out."""
        sleep = asyncio.sleep
        sing = self.bot.say
        sleep = asyncio.sleep
        await sleep(1.0)
        await sing("Fuck this shit I'm out.")
        await sleep(1.2)
        await sing("Mmmmmm Hmmmmm")
        await sleep(0.1)
        await sing("Fuck this shit I'm out.")
        await sleep(1.2)
        await sing("No thanks.")
        await sleep(0.1)
        await sing("Don't mind me.")
        await sleep(1.2)
        await sing("Imma just grab my stuff and leave.")
        await sleep(2.0)
        await sing("Excuse me please.")
        await sleep(1.1)
        await sing("Fuck this shit I'm out.")
        await sleep(1.2)
        await sing("NOPE!")
        await sleep(0.5)
        await sing("Fuck this shit I'm out.")
        await sleep(1.2)
        await sing("Alright then.")
        await sleep(0.5)
        await sing("I dunno know what the fck just happened.")
        await sleep(1.8)
        await sing("But I don't really care.")
        await sleep(1.2)
        await sing("Imma get the fuck up outta here.")
        await sleep(1.5)
        await sing("Fuck this shit I'm out.")
        await sleep(1.5)
        await sing("https://youtu.be/9wO5TnYaJ4o?t=53s")

    @commands.command()
    async def princeofbelair(self, user : discord.Member=None):
        sleep = asyncio.sleep
        sing = self.bot.say
        if user == None:
            await sing("https://www.youtube.com/watch?v=AVbQo3IOC_A")
            await sleep(3)
            await sing("Now this is a story, all about how my life got flipped, turned upside down.")
            await sleep(4)
            await sing("And I like to take minute just sit right there, I'll tell you how I became the price of a town called Bel Air.")
            await sleep(23)
            await sing("In west Philadalphea born 'n raised, on the play ground where I spent most of my days.")
            await sleep(5)
            await sing("Chillin' out, maxin' relaxin' and all cool and all shooting some bball outside of the school.")
            await sleep(5)
            await sing("When a couple of guys said we were up to no good! Started making trouble in my neighborhood.")
            await sleep(4)
            await sing("I got in one little fight and my mom got scared and said 'you're moving to your auntie and uncle in Bel Air'.")
            await sleep(5)
            await sing("I begged and pleaded with her to have the day but she pack my suit-case and sent me on my way.")
            await sleep(4)
            await sing("She gave me a kiss and she gave me my ticket, I put my walkman on and said 'I might as well kick it'.")
            await sleep(5)
            await sing("First class, sho' this is bad, drinking orange juice outta a champange glass.")
            await sleep(5)
            await sing("Is this what the people of Bel Air living like?")
            await sleep(2)
            await sing("Hmm, this might be all right.")
            await sleep(2)
            await sing("But wait I hear the prissy, booze, wine and all.")
            await sleep(3)
            await sing("Is this the type of place they should send this cool-cat?")
            await sleep(2)
            await sing("I don't think so, I'll see when I get there, I hope they're prepared for The Prince of Bel Air.")
            await sleep(22)
            await sing("Well I, the plane landed and when I came out, there was a dude who looked like a cop standing there with my name out, I ain't trying to get arrested yet I just got here!")
            await sleep(8)
            await sing("I sprang with the quickness the lightning disappeared.")
            await sleep(2)
            await sing("I whistled for a cab, and when it came near, the license plate said fresh and had a dice in the mirror.")
            await sleep(6)
            await sing("If anything I could sing this cat was rare, but I thought 'man forget yet, yo homes the Bel Air'.")
            await sleep(13)
            await sing("I pulled up to the house about 7 or 8 and I yelled to the cabbie 'yo homes smell ya later'.")
            await sleep(6)
            await sing("Looked at my kingdom, I was finally here to sit on my throne as The Prince of Bel Air.")
        else:
            await sing("https://www.youtube.com/watch?v=AVbQo3IOC_A")
            await sleep(3)
            await sing("Now this is a story, all about how my life got flipped, turned upside down.")
            await sleep(4)
            await sing("And I like to take minute just sit right there, I'll tell you how I became the price of a town called Bel Air.")
            await sleep(23)
            await sing("In west Philadalphea born 'n raised, on the play ground where I spent most of my days.")
            await sleep(5)
            await sing("Chillin' out, maxin' relaxin' and all cool and all shooting some bball outside of the school.")
            await sleep(5)
            await sing("When a couple of guys said we were up to no good! Started making trouble in my neighborhood.")
            await sleep(4)
            await sing("I got in one little fight and my mom got scared and said 'you're moving to your auntie and uncle in Bel Air'.")
            await sleep(5)
            await sing("I begged and pleaded with her to have the day but she pack my suit-case and sent me on my way.")
            await sleep(4)
            await sing("She gave me a kiss and she gave me my ticket, I put my walkman on and said 'I might as well kick it'.")
            await sleep(5)
            await sing("First class, sho' this is bad, drinking orange juice outta a champange glass.")
            await sleep(5)
            await sing("Is this what the people of Bel Air living like?")
            await sleep(2)
            await sing("Hmm, this might be all right.")
            await sleep(2)
            await sing("But wait I hear the prissy, booze, wine and all.")
            await sleep(3)
            await sing("Is this the type of place they should send this cool-cat?")
            await sleep(2)
            await sing("I don't think so, I'll see when I get there, I hope they're prepared for {}.".format(user.mention))
            await sleep(22)
            await sing("Well I, the plane landed and when I came out, there was a dude who looked like a cop standing there with my name out, I ain't trying to get arrested yet I just got here!")
            await sleep(8)
            await sing("I sprang with the quickness the lightning disappeared.")
            await sleep(2)
            await sing("I whistled for a cab, and when it came near, the license plate said fresh and had a dice in the mirror.")
            await sleep(6)
            await sing("If anything I could sing this cat was rare, but I thought 'man forget yet, yo homes the Bel Air'.")
            await sleep(13)
            await sing("I pulled up to the house about 7 or 8 and I yelled to the cabbie 'yo homes smell ya later'.")
            await sleep(6)
            await sing("Looked at my kingdom, I was finally here to sit on my throne as {}.".format(user.mention))
            
    @commands.command(name="heman", aliases=["heeman"])
    async def heman(self):
        """HEYYEYAAEYAAAEYAEYAA."""
        sleep = asyncio.sleep
        sing = self.bot.say
        song = self.bot.say
        await song("https://www.youtube.com/watch?v=ZZ5LpwO-An4")
        await sleep(4)
        await sing("And so I cry sometime when I'm lying in bed.")
        await sleep(3)
        await sing("To just give it all up, what's in my head.")
        await sleep(4)
        await sing("And I! I'm feeling a little peculiar.")
        await sleep(6)
        await sing("And so I wake in the morning and I step outside.")
        await sleep(4)
        await sing("And I take a deep breath and get real high.")
        await sleep(3)
        await sing("And I, scream from the top of my lungs, what's going on?!")
        await sleep(6)
        await sing("And I say HEY YEAH YEAH YEAH YEAH, HEY YEAH YEAH, I SAY HEY, WHAT'S GOING ON!?")
        await sleep(12)
        await sing("And I say, HEY YEAH YEAH YEAH YEAH, HEY YEAH YEAH, I SAY HEY, WHAT'S GOING ON!?")
        await sleep(12)
        await sing("And he tries.")
        await sleep(3)
        await sing("Oh my god do I try.")
        await sleep(4)
        await sing("I try all the time, in this institution.")
        await sleep(7)
        await sing("And he prays!")
        await sleep(3)
        await sing("Oh my god do I pray.")
        await sleep(3)
        await sing("I pray every single day!")
        await sleep(3)
        await sing("MYAAAH")
        await sing("FOR A REVOLUTION!")
        await sleep(3)
        await sing("And I say, HEY YEAH YEAH YEAH YEAH, HEY YEAH YEAH, I SAY HEY, WHAT'S GOING ON!?")
        await sleep(12)
        await sing("And I say, HEY YEAH YEAH YEAH YEAH, HEY YEAH YEAH, I SAY HEY, WHAT'S GOING ON!?")

        
def setup(bot):
    bot.add_cog(lyriccommands(bot))